import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const geistSans = localFont({
  src: [
    {
      path: '../../public/fonts/Geist-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geist-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-geist-sans",
  display: 'swap',
});

const geistMono = localFont({
  src: [
    {
      path: '../../public/fonts/GeistMono-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GeistMono-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-geist-mono",
  display: 'swap',
});

const michroma = localFont({
  src: '../../public/fonts/Michroma-Regular.ttf',
  variable: "--font-michroma",
  weight: '400',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${michroma.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
