services:
  frontend:
    image: Qrdia/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - ./frontend/.env:/app/.env
    tty: true
    stdin_open: true

  backend:
    image: Qrdia/backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./cli:/app/cli
      - /var/run/hostapd:/var/run/hostapd:rw
      - /tmp:/tmp:rw
    environment:
      - CLI_SCRIPT_PATH=/app/cli
    privileged: true
    depends_on:
      - frontend
